// src/react/Counter.jsx
import { useState, useRef, useEffect } from "react";

import styles from './App.module.css';

export const Counter = ({ label = 'React Counter', increment = 1, onReset }) => {
  const [count, setCount] = useState(0);
  const incrementVal = useRef();

  useEffect(() => {
    incrementVal.current = increment;
  }, [increment]);

  useEffect(() => {
    const onTick = () => {
      setCount(current => current + incrementVal.current);
    };

    setInterval(onTick, 1000);
  }, []);

  const resetCount = () => { setCount(0); onReset && onReset(); };

  return <div className={styles.counter}>{label}: {count} <button onClick={resetCount}>Reset</button></div>;
}

// src/solid/Counter.jsx
import { createSignal } from "solid-js";

import styles from './App.module.css';

export function Counter(props) {
  const [count, setCount] = createSignal(0);

  setInterval(() => setCount(count() + props.increment), 1000);
  const resetCount = () => { setCount(0); props.onReset && props.onReset(); };

  return <div class={styles.counter}>{props.label || 'Solid.js Counter'}: {count()} <button onClick={resetCount}>Reset</button></div>;
}
